[package]
name = "steamid-ng"
version = "0.1.1"
authors = ["Moses Miller <Majora320@gmail.com>"]
description = "An easy-to-use steamid type with functions to parse and render steam2 and steam3 IDs"
repository = "https://github.com/Majora320/steamid-ng"
readme = "README.md"
keywords = ["steam", "steamid", "parse", "parser"]
categories = ["parser-implementations", "games"]
license = "MIT"

[dependencies]
enum_primitive = "0.1.1"
lazy_static = "0.2.8"
try_opt = "0.1.1"
regex = "0.2.2"

[badges]
maintenance = { status = "passively-maintained" }
travis-ci = { repository = "Majora320/steamid-ng", branch = "master" }
